// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestingNet6EFCore6.Data;

#nullable disable

namespace TestingNet6EFCore6.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230331144816_PeopleParentGroups")]
    partial class PeopleParentGroups
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("TestingNet6EFCore6.Models.ParentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ParentGroups");
                });

            modelBuilder.Entity("TestingNet6EFCore6.Models.People", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("TestingNet6EFCore6.Models.PeopleParentGroup", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeoplePersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonId", "ParentGroupId");

                    b.HasIndex("ParentGroupId");

                    b.HasIndex("PeoplePersonId");

                    b.ToTable("PeopleParentGroups");
                });

            modelBuilder.Entity("TestingNet6EFCore6.Models.PeopleParentGroup", b =>
                {
                    b.HasOne("TestingNet6EFCore6.Models.ParentGroup", "ParentGroup")
                        .WithMany()
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingNet6EFCore6.Models.People", "People")
                        .WithMany()
                        .HasForeignKey("PeoplePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentGroup");

                    b.Navigation("People");
                });
#pragma warning restore 612, 618
        }
    }
}
